org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.20.2)
forge_version=47.4.10
forge_version_range=[47.4.1,)
loader_version_range=[47,)

mixin_processor_version=0.8.7

## Mod Properties

mod_id=tieredtools
mod_name=Tiered Tools
mod_license=The MIT License (MIT)
mod_version=0.0.1
mod_group_id=com.reasure.tieredtool
mod_authors=reasure
mod_description=This mod completely overhauls Minecraft's tool progression system. \
You can no longer craft higher-tier tools directly. \
Instead, you must upgrade them step-by-step using a Smithing Table.
mod_issue_tracker_url=https://github.com/reasure3/TieredTools/issues
mod_update_json_url=https://raw.githubusercontent.com/reasure3/MinecraftModVersions/refs/heads/main/neoforge/tieredtools.json
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/tiered-tools
mod_logo_file=logo.png

## Dependencies Properties

jei_mc_version=1.20.1
jei_version=15.20.0.116
emi_version=1.1.22+1.20.1

# For Convenience
patchouli_version=1.20.1-84.1-FORGE
jade_version=11.13.2+forge
